// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeRoutes.Data;
using SafeRoutes.Models;
using System;

#nullable disable

namespace SafeRouts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
                
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeRoutes.Models.InternalNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("NoteID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ReportID");

                    b.ToTable("InternalNotes");
                });

            modelBuilder.Entity("SafeRoutes.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("ReportID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });
            modelBuilder.Entity<InternalNote>()
            .HasOne(n => n.CreatedByUser)
            .WithMany()
            .HasForeignKey(n => n.CreatedByUserID)
            .OnDelete(DeleteBehavior.NoAction);
            modelBuilder.Entity("SafeRoutes.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<decimal?>("AIConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AIExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CitizenUserID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStatusID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriorityID")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("CitizenUserID");

                    b.HasIndex("CurrentStatusID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("SectorID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToTeamID")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("AssignedByUserID");

                    b.HasIndex("AssignedToTeamID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportAssignments");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportPriority", b =>
                {
                    b.Property<int>("PriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PriorityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PriorityID");

                    b.ToTable("ReportPriorities");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportID");

                    b.HasIndex("SectorID");

                    b.ToTable("ReportSectors");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("ReportStatuses");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportStatusHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("NewStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("ChangedByUserID");

                    b.HasIndex("NewStatusID");

                    b.HasIndex("OldStatusID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportStatusHistory");
                });

            modelBuilder.Entity("SafeRoutes.Models.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorID");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("SafeRoutes.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("SectorID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SafeRoutes.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorID")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("SectorID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SafeRoutes.Models.InternalNote", b =>
                {
                    b.HasOne("SafeRoutes.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SafeRoutes.Models.Notification", b =>
                {
                    b.HasOne("SafeRoutes.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRoutes.Models.Report", b =>
                {
                    b.HasOne("SafeRoutes.Models.User", "CitizenUser")
                        .WithMany()
                        .HasForeignKey("CitizenUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.ReportStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.ReportPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");

                    b.Navigation("CitizenUser");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Priority");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportAssignment", b =>
                {
                    b.HasOne("SafeRoutes.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.Team", "AssignedToTeam")
                        .WithMany()
                        .HasForeignKey("AssignedToTeamID");

                    b.HasOne("SafeRoutes.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserID");

                    b.HasOne("SafeRoutes.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToTeam");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportSector", b =>
                {
                    b.HasOne("SafeRoutes.Models.Report", "Report")
                        .WithMany("ReportSectors")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.Sector", "Sector")
                        .WithMany("ReportSectors")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SafeRoutes.Models.ReportStatusHistory", b =>
                {
                    b.HasOne("SafeRoutes.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.ReportStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeRoutes.Models.ReportStatus", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusID");

                    b.HasOne("SafeRoutes.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SafeRoutes.Models.Team", b =>
                {
                    b.HasOne("SafeRoutes.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SafeRoutes.Models.User", b =>
                {
                    b.HasOne("SafeRoutes.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SafeRoutes.Models.Report", b =>
                {
                    b.Navigation("ReportSectors");
                });

            modelBuilder.Entity("SafeRoutes.Models.Sector", b =>
                {
                    b.Navigation("ReportSectors");
                });
#pragma warning restore 612, 618
        }
    }
}
